import { QuestionInfo } from "./interfaces";

// Data for variation
export const eventNames: string[] = [
  `Tech Innovation Summit`,
  `Summer Beach Bash`,
  `International Food Festival`,
  `Comic Con Cosplay Party`,
  `Jazz Under the Stars`,
  `Fitness Expo & Wellness Retreat`,
  `Wine Tasting Soirée`,
  `Scary Movie Marathon Madness`,
  `Electric Dance Music Festival`,
  `Gaming Convention Spectacular`,
  `Artisan Craft Market`,
  `Interior Desginer Convention`,
  `Winter Wonderland Gala`,
  `Sustainable Living Symposium`,
  `Speed Dating Mixer`,
  `Yoga and Meditation Retreat`,
  `Automotive Expo and Car Show`,
  `Masquerade Ball`,
  `Charity Fundraising Gala`,
  `Science Fiction Film Festival`,
  `Global Fashion Week`,
  `Oktoberfest Celebration`,
  `Doggie Costume Parade`,
  `Outdoor Adventure Retreat`,
  `Music & Arts Festival`,
  `Harry Potter Wizarding World Experience`,
  `Tropical Luau Beach Party`,
  `Vintage Flea Market`,
  `Robotics Competition Showcase`,
  `Holiday Cookie Decorating Workshop`,
  `Broadway Musical Revue`,
  `Career Development Conference`,
  `Italian Food Fair`,
  `Retro 80s Dance Party`,
  `Photography Workshop & Exhibition`,
  `DJ Pool Party`,
  `Farm-to-Table Dinner`,
  `Travel and Adventure Expo`,
  `DIY Craft and Hobby Fair`,
  `Gaming LAN Party`,
  `Dog Adoption Fair`,
  `Entrepreneurship Summit`,
  `Beer and BBQ Festival`,
  `Wedding Expo Extravaganza`,
  `Outdoor Music Jam Session`,
  `International Film Festival Experience`,
];
export const eventDescriptions = [
  "A gathering focused on showcasing and discussing the latest advancements and trends in technology and innovation.",
  "An exhilarating beach party, featuring music, games, beach volleyball, and much more!",
  "A multicultural event offering a wide variety of cuisines from around the world for attendees to sample and enjoy.",
  "A celebration where enthusiasts of comic books, movies, and pop culture come together. Cosplay your favorite characters and prepare to geek out!",
  "An outdoor musical event featuring live jazz performances held during the evening under the open sky.",
  "A gathering focused on promoting physical fitness, health, and overall wellness through workshops, seminars, demonstrations, and workouts.",
  "An elegant social event centered around the sampling and appreciation of various wines, accompanied by gourmet food pairings.",
  "Watch a series of scary movies back-to-back in this immersive and thrilling movie-watching experience.",
  "Featuring all your favourite EDM performs and DJs. Enjoy dancing under vibrant light shows.",
  "A convention dedicated to gaming culture, including video games, board games, cosplay, tournaments, and industry announcements.",
  "A marketplace showcasing handcrafted items and artisanal goods, providing a platform for local artists and craftsmen to display and sell their creations.",
  "Calling all professionals and enthusiasts in the interior design industry. Enjoy workshops, seminars, and exhibitions of design trends and innovations in interior design.",
  "Step into a magical winter wonderland and indulge in an evening of elegance and enchantment! Join us for a glamorous gala filled with dazzling lights, festive decorations, live entertainment, gourmet dining, and unforgettable moments. Embrace the spirit of the season and create cherished memories at our Winter Wonderland Gala.",
  "Discover innovative ways to live sustainably at our Sustainable Living Symposium. Join experts, engage in discussions, and explore practical solutions for a greener future.",
  "Find love in a flash at our Speed Dating Mixer! Meet new people, enjoy lively conversations, and who knows, you might just meet your perfect match.",
  "Embark on a journey of self-discovery and relaxation at our Yoga and Meditation Retreat. Reconnect with your inner peace and find harmony amidst serene surroundings.",
  "Rev up your engines and experience the thrill at our Automotive Expo and Car Show. Explore the latest models, classic cars, and cutting-edge technology.",
  "Step into a world of mystery and intrigue at our Masquerade Ball. Dress to impress, dance the night away, and revel in the enchantment of the evening.",
  "Make a difference while having a fabulous time at our Charity Fundraising Gala. Support noble causes, enjoy gourmet cuisine, and partake in charitable auctions.",
  "Immerse yourself in the wonders of science fiction at our Science Fiction Film Festival. Experience thrilling adventures, futuristic worlds, and captivating stories.",
  "Experience the glamour and excitement of the fashion world at our Global Fashion Week. Witness stunning runway shows, exclusive collections, and trendsetting designs.",
  "Raise your stein and join the festivities at our Oktoberfest Celebration. Enjoy traditional German food, lively music, and plenty of frothy beer.",
  "Let your furry friend shine at our Doggie Costume Parade! Dress up your pooch, strut your stuff, and compete for prizes in this paw-some event.",
  "Embark on an adrenaline-fueled escapade at our Outdoor Adventure Retreat. From hiking to zip-lining, challenge yourself and explore the great outdoors.",
  "Immerse yourself in creativity and culture at our Music & Arts Festival. Enjoy live performances, art exhibits, workshops, and interactive installations.",
  "Step into the magical world of Hogwarts at our Harry Potter Wizarding World Experience. Cast spells, attend classes, and embark on fantastical adventures.",
  "Escape to paradise at our Tropical Luau Beach Party. Enjoy tropical cocktails, live music, fire dancers, and the laid-back vibes of island life.",
  "Unearth hidden treasures at our Vintage Flea Market. Browse through unique finds, retro collectibles, and one-of-a-kind treasures.",
  "Witness cutting-edge technology and innovation at our Robotics Competition Showcase. Cheer on competitors, marvel at robotic creations, and be inspired by the future.",
  "Get into the holiday spirit at our Holiday Cookie Decorating Workshop. Create festive treats, indulge your sweet tooth, and spread joy with delicious cookies.",
  "Experience the magic of Broadway at our Broadway Musical Revue. Enjoy show-stopping performances, iconic tunes, and the glitz and glamour of musical theater.",
  "Take your career to new heights at our Career Development Conference. Gain valuable insights, network with industry professionals, and explore new opportunities.",
  "Savor the flavors of Italy at our Italian Food Fair. Indulge in authentic dishes, sample Italian wines, and experience the culinary delights of Italy.",
  "Travel back in time and dance the night away at our Retro 80s Dance Party. Put on your neon attire, groove to classic hits, and relive the glory days of the 80s.",
  "Capture the moment and unleash your creativity at our Photography Workshop & Exhibition. Learn new techniques, showcase your work, and be inspired by fellow photographers.",
  "Dive into the ultimate poolside party experience at our DJ Pool Party! Immerse yourself in the pulsating beats of top DJs, bask in the sun, and cool off in the refreshing pool waters.",
  "Savor the bounty of the season at our Farm-to-Table Dinner. Enjoy farm-fresh ingredients, locally sourced produce, and exquisite culinary creations.",
  "Embark on your next adventure at our Travel and Adventure Expo. Discover exciting destinations, plan your next getaway, and make unforgettable memories.",
  "Unleash your inner artist at our DIY Craft and Hobby Fair. Explore a variety of crafts, unleash your creativity, and find inspiration for your next project.",
  "Level up your gaming experience at our Gaming LAN Party. Compete with friends, meet fellow gamers, and enjoy non-stop gaming action.",
  "Find your new best friend at our Dog Adoption Fair. Meet adorable dogs in need of loving homes, learn about pet care, and make a furry friend for life.",
  "Ignite your entrepreneurial spirit at our Entrepreneurship Summit. Learn from industry leaders, network with fellow entrepreneurs, and turn your ideas into reality.",
  "Satisfy your cravings at our Beer and BBQ Festival. Indulge in mouthwatering barbecue dishes, sample craft beers, and enjoy live music and entertainment.",
  "Plan your dream wedding at our Wedding Expo Extravaganza. Discover bridal trends, meet wedding vendors, and turn your wedding dreams into reality.",
  "Jam out under the stars at our Outdoor Music Jam Session. Enjoy live music performances, sing along to your favorite tunes, and dance the night away.",
  "Experience the magic of cinema at our International Film Festival Experience. Watch award-winning films, meet filmmakers, and immerse yourself in the world of cinema."
];
export const locations: string[] = [
  "The Plaza Hotel, New York City, USA",
  "Sydney Opera House, Sydney, Australia",
  "Palais des Congrès de Paris, Paris, France",
  "Los Angeles Convention Center, Los Angeles, USA",
  "Tokyo Big Sight, Tokyo, Japan",
  "ExCeL London, London, UK",
  "Jacob K. Javits Convention Center, New York City, USA",
  "Shanghai New International Expo Centre, Shanghai, China",
  "Suntec Singapore Convention & Exhibition Centre, Singapore",
  "Cape Town International Convention Centre, Cape Town, South Africa",
  "Melbourne Convention and Exhibition Centre, Melbourne, Australia",
  "Bella Center Copenhagen, Copenhagen, Denmark",
  "Moscone Center, San Francisco, USA",
  "Fira Barcelona Gran Via, Barcelona, Spain",
  "Centro Citibanamex, Mexico City, Mexico",
  "Vancouver Convention Centre, Vancouver, Canada",
  "RAI Amsterdam, Amsterdam, Netherlands",
  "Hilton Tokyo, Tokyo, Japan",
  "Messe Frankfurt, Frankfurt, Germany",
  "Kuala Lumpur Convention Centre, Kuala Lumpur, Malaysia",
  "Dubai World Trade Centre, Dubai, UAE",
  "Hong Kong Convention and Exhibition Centre, Hong Kong",
  "Sands Expo and Convention Centre, Singapore",
  "Marina Bay Sands, Singapore",
  "Palacio de Exposiciones y Congresos de Granada, Granada, Spain",
  "Fira de Barcelona Montjuïc, Barcelona, Spain",
  "Messe Berlin, Berlin, Germany",
  "International Convention Centre Sydney, Sydney, Australia",
  "ACC Liverpool, Liverpool, UK",
  "Las Vegas Convention Center, Las Vegas, USA",
  "JW Marriott Marquis Dubai, Dubai, UAE",
  "Expo Guadalajara, Guadalajara, Mexico",
  "Orange County Convention Center, Orlando, USA",
  "San Diego Convention Center, San Diego, USA",
  "Hilton Istanbul Bosphorus, Istanbul, Turkey",
  "Messe Düsseldorf, Düsseldorf, Germany",
  "Manchester Central Convention Complex, Manchester, UK",
  "BITEC Bangkok International Trade & Exhibition Centre, Bangkok, Thailand",
  "Brisbane Convention & Exhibition Centre, Brisbane, Australia",
  "Sands Expo, Las Vegas, USA",
  "Bella Center, Copenhagen, Denmark",
  "Messe Stuttgart, Stuttgart, Germany",
  "Seoul Convention and Exhibition Center, Seoul, South Korea",
  "Jumeirah Emirates Towers, Dubai, UAE",
  "Suntec Singapore International Convention and Exhibition Centre, Singapore",
  "Rome Convention Center, Rome, Italy",
  "International Convention Centre, Durban, South Africa",
  "Estrel Berlin, Berlin, Germany"
];
export const ticketTypes: string[] = [
  "VIP",
  "Ground",
  "All-Day",
  "Platinum",
  "Early Bird",
  "General Admission",
  "Exclusive",
  "Backstage",
  "Family Pass",
  "Student Pass",
  "Group Pass",
  "Senior Pass",
  "Weekend Pass",
  "Child Pass",
  "Day Pass",
  "Premium Pass",
  "Corporate Pass",
  "Artist Pass",
  "Volunteer Pass",
];

export const descriptions: { [key: string]: string } = {
  VIP: "Enjoy exclusive access with priority seating, backstage tours, and meet-and-greets.",
  Ground: "Access to all ground events, perfect for those who love to explore.",
  "All-Day":
    "Spend the entire day at the event with access to all general areas.",
  Platinum: "The ultimate experience with all-access passes and premium perks.",
  "Early Bird":
    "Special pricing for early purchasers, with the same benefits as General Admission.",
  "General Admission":
    "Standard access to the event, a great way to enjoy the day.",
  Exclusive:
    "Limited tickets offering private sessions and unique experiences.",
  Backstage:
    "Behind-the-scenes access with a chance to meet the performers or speakers.",
  "Family Pass": "Access for the whole family to enjoy the event together.",
  "Student Pass": "Discounted tickets for students with valid ID.",
  "Group Pass": "Special rates for groups attending the event together.",
  "Senior Pass": "Discounted tickets for seniors aged 65 and above.",
  "Weekend Pass": "Access to the event for the entire weekend.",
  "Child Pass": "Tickets for children under a certain age, usually accompanied by an adult.",
  "Day Pass": "Access to the event for a single day.",
  "Premium Pass": "Enhanced access with additional perks and privileges.",
  "Corporate Pass": "Tickets purchased by companies for their employees or clients.",
  "Artist Pass": "Access granted to artists participating or performing at the event.",
  "Volunteer Pass": "Tickets provided to volunteers helping with the event.",
};
export const questions: QuestionInfo[] = [
  { question: "First Name", required: true },
  { question: "Last Name", required: true },
  { question: "How did you find out about this event?", required: true },
  {
    question: "How many events have you attended in the past year?",
    required: false,
  },
  { question: "How many people are in your company?", required: false },
];
export const artworkUrls: string[] = [
  "bafkreifuuae4uzclz5futlfqrq43aqk6peb26er6dz7nhrserr6f7zqrqy",
  "bafkreifgjnfpzjpfijndodzqw262z2xrec3qjfut5nyoekbysozwwpqakq",
  "bafkreibjwsx2xysmyirzxs2javoef5fsm4hc6qijd5eozab7vczch7emue",
  "bafybeievxgehd4c32rw3my4442hz7m7sg4fzqwqcj3svik4odqj2abvtki",
  "bafkreidnunjx54nuihtdb5bepjddg4x46lgqwjnxh4pqkoeghwmk5wzori",
  "bafkreif64jwdpoucvnwcfomgpei4tohrausmejkj4xff373lbowejrg2gy",
  "bafkreihnrxt5w63sn72yv57gmhkt3vrgivpmj5jos3pvkgat2fly7byuxq",
  "bafkreidxv3kceqcww3pbafegj6umcm4nvrrogncmaxdaej4usprvijru7m",
  "bafkreifndei6o3v3vnyaukfq6vo3ibtmj4bxtsahhs25nb5khfeqy5hliu",
  "bafkreiaopinppelx4krmjfwum6dca3v3h5idhkolwqgzehhfwvfmctfqam",
  "bafkreifdjyk37zz42ndytqtqyhla7p2er6w2trooe2nlobhqgmvjcvpypy",
  "bafkreicgl5j6s23zsngebxogczasduna4ww5w7gs6jntuwode7fcwoddrm",
  "bafybeickeylezcogp4emkhnm7d4klxddryhylyzqu6czpq7fepbebpdovu",
  "bafkreib5txxenzq4bta7xytarnjqwrkgludohyq4gkw6wnu7blosefjixy",
  "bafkreifs2k66k3vvc4nkfqx2ywgdkwcn2bi3i5pomdlox3nmkwkq2advma",
  "bafkreiajkjuu53h2p3gd577xwekzynbtbmvoptze3eesi7zxilhwvj2xlm",
  "bafkreifgfckg5xmczlffvmtwpelf64vg3mecwztgfvo4v3qs6ghxa2pzzq",
  "bafkreifxmezugfqx5axuthlvqa62ejznycelk3f63tabsj45cwiv3ezfkm",
  "bafkreiawoi3ecnxe5uo4f3wovzzlm4qvbl63opbajaxmbkqr7w3utunq7u",
  "bafkreidnluh6q766cvfjszix6obhvywdniu5nwawrrh6qudupg4weuwhei",
  "bafkreicn4vlxxvyhambth6qfg6o4qmzotpr6zyql7ovdxvegzxrme2my5q",
  "bafkreigzg3ta2vuiqj657tz5ke6uw4vgrkdoluywxre5kt4gcqo47m2mdq",
  "bafkreiewcnq7lasjt4wcy7flpp5ysryboj2mjzraeqdryukrn6xufloc6a",
  "bafkreigsivx5thkfjxsimnsztb6bd2cff2wflxa6gjm2azsf2zsh224rru",
  "bafkreieukujzhtiuqxzgejqodzka5mbjk2au4hcqdowr63t2srp2fpg26y",
  "bafkreiewz5acegscg4lk4vwzng3vsdpkaw2ikix22cvfpoh6upkvctyiza",
  "bafkreidhq3ixy3py676whnekbw7gnjefukbhrzx7heknjsllqne7u4y7xy",
  "bafkreib73545shvsd4p4qfto3irwzqwlzugm6gbdqspt4jixbyyyftqx7m",
  "bafkreifg4xyx6kyuhpgir3d6lrrss3nwxkds5pjytzmqib7f245zhos5yu",
  "bafkreieot5emqeyfsvk22dqxyjfk5mcsj5fsy7f7casl2of6pmdd65b6oe",
  "bafkreiavmtau6kftuoaulwoasay67rchowynbcyeh5jjle3j3wp7eby7uu",
  "bafkreih2pz677gzmm4ecac6gfymwjg7a3axdfzdt4avjur2hr53fqpj2iq",
  "bafkreia5zi3dbvem5zgankbr4dmjsnedrd3kggywgd6vy6ttwbtnunhorq",
];

export const ticketArtworkUrls: string[] = [
  "bafkreifuuae4uzclz5futlfqrq43aqk6peb26er6dz7nhrserr6f7zqrqy",
  "bafkreifgjnfpzjpfijndodzqw262z2xrec3qjfut5nyoekbysozwwpqakq",
  "bafybeibddhylbfgow5ibibi5w5xivolm46r43qcsasdpox7uuuzvcqq6my",
  "bafkreiaxdcf5mpyku6753je6mkjekngkcx4dqn3rvinw6gtpjcjcvyyuou",
  "bafkreiai4dybpvndyv6emcfj2hee2e2ld3o4jppdi2doy7agjaq3vx3ecm",
  "bafkreic7skplx22lanhiqix3ojfpw3fx6oqub3ji5swmlhycsrxcrhinwu",
  "bafkreid3mtsjwnde6g5q52df2hpfpb5i234ppww7jfiqx4jecineo4bzbu",
  "bafkreicasv3p6yyj5cmrr4dcygycjnte7pnzwcegtrrjnyjz5goho6czha",
  "bafkreig3d5rbjhfdihasczn5klkp5axazhohjp62evg6u6hbgqozpmexs4",
  "bafkreifwsrd3jioxokxvvr66jkla4hn2ozx5jdhrp7xyrkbmauuvfqv3yi",
  "bafkreifnchkhp6hdcicdbomes5wgg5cnglajo7gx3p2zilthakznhrvjo4",
  "bafkreiajmjlmg63tejtmzqv6j7oqq7ptt46g5vooouuoewwoog2z5kz6ya",
  "bafkreiaw6wshhrimhajilz3eciemc3rrvsejwa67cg3obzkpkyy3fdcsqu",
  "bafkreic3pq6rrqegfs6xiageud5un4uwpdvlbcbqwekfv6xhuneqfmqkhy",
  "bafkreiclknrt3apvo4qqu7zk3yvxddivvrowyugksp4vkxnplkgzmvdkr4",
  "bafkreiajo37xjmzzfsmq2zkuyebq4lmgavvofdo62eqt6jpefvahwxhusm",
  "bafkreibhymlalrs5ex2dapnstus6x2ixddvh3limafhqojcgz2atpwibwe",
  "bafkreih5nece2gaw43mmqvwyszcuq7rj3mygvc7kxjxniopkxerrtttsoe",
  "bafkreieot5emqeyfsvk22dqxyjfk5mcsj5fsy7f7casl2of6pmdd65b6oe",
  "bafkreiaegchkhjwayk73ds26tcwx3puarkavytf67utwom4whp5fmvbr64",
  "bafkreiapywnmku5sl3k2granzyog45mfypo6xqmfjxbawxumgbtgwc3ili",
  "bafybeigz62b2tgynln2iggrdsimocmmtl2bmjmjrhxyqlbeqlfzwfm7fhi",
  "bafkreieggevrdy5rdd7yh63nllcmajxwbeqgvk4fpsd6p34dryacpgoinm",
  "bafkreifuweie7eqqwleh5kxqhtlahed7hunltjyn64tuhw3f5tmz5tjrte",
  "bafkreieh7w3y3bdgjl7frp2eaflny2uylt6va4e4eou5zt4g2i47gy4cum",
  "bafkreiec6zibym4d6yrvz7sjew64dvxq6w2lfw2o3dtzeb22dzkndtva2y",
  "bafkreihlpbepkp4u6cnc7ayjxtbhxuelltmzopqqdfealnrctfljfe3a2m",
  "bafkreicytziwkf42z5tgkaoyakzvvfovsnw6jofwfxcp66gvomlchaosg4",
  "bafkreif46zxwlzofcntjuuxt25eeasouccsbddyj7hlzfgdfgai7oj7yni",
  "bafkreicxjj72njdcddxkyjlsvew2vkrv63mvple7ctm32hf2su5kyruqcu",
  "bafkreiaivtqbev5jlnqijw2767iwaiulfcrlyvsgzsy4qxf3ije7a7d3fq",
  "bafkreibhfytyblp3xx2kbq625bmfqmj733mx4tj72thji246otv2gzzdsi",
  "bafkreigubkhodd54azsuqixvvdln7h6k3xneyjybsihoe2b7piokvspoi4",
  "bafkreicwjgwuiqxf5kmuhh67xrqdvwagvzsw36gy3nhsdjupsjrjkgobjq",
  "bafkreic43dug7dhuhc6hhhv75akmqhlr32azqcdp7nlixpb3eexv5bktgi",
  "bafkreic43dug7dhuhc6hhhv75akmqhlr32azqcdp7nlixpb3eexv5bktgi",
  "bafkreicqfu6yjk5gp6zlw5bq3nze4swlu35oaydabbfssu4g3m2nenilry",
  "bafkreidq6cvkvbasv6kyyj6jwv73togjwdyfndaubsieoptzrbpbw5as4a",
  "bafybeick45cfjscajfya2aacos27hejp2heqqihsrb7uj2n3adgztje2du",
  "bafybeigxicbe6iduiwfesndu45r7f4ietbynzisg22yrixlwlsvue5uqza",
  "bafkreif64tonprq2dimk775ddbfg64qqcgjm7jljn65qo5mvtzt65i2xk4",
  "bafybeihj6kqj2rnieu6d5aluywdcnsg44oxik6sc3ng3fz3n5h22o4nx6a",
];
